### PR TITLE
Add the posibility of use an attenuator inline with the S21 (CH1) input

### PR DESCRIPTION
**Pull request by stdevPavelmc**
Related to #125, see the comments on the issue.

I opted for the long math solution, maybe there are other more elegant or simpler.

Cheers

### CODE REVIEW

**Comment by zarath** [comment]
Why not accepting negative attenuation. If you have a known applification.

Type hint of correction method should be list of Datapoint, not a single datapoint

**Comment by stdevPavelmc** [comment]
> Why not accepting negative attenuation. If you have a known applification.
> 
> Type hint of correction method should be list of Datapoint, not a single datapoint

Negative attenuation is indeed amplification or positive gain! (At least in my experience and life with RF)

We are talking about the attenuators to keep levels in the amplifier and nanovna happy & safe, so we are referring to the attenuators in place, not the amplification in the devices under test. 

Technically and 99% of the time when you say "attenuation" you are taking about a negative gain network, when you states a "negative attenuation circuit" you are grammatically correct, but is more correct to talk about a gain of 'X' dB.

Read this: the circuit has an attenuation of 3 db (that is a gain of -3dB)

Is just semantics I know, but I think that stating a negative attenuation is more confusing that just stating the module of the attenuators you place in line with the RF path.

About the Datapoint list issue, I will take a look ASAP, thanks for spotting that.

**Comment by gaionim** [comment]
It seems that correct only real part.
I think it is better this way
`
def corrAttData(data: Datapoint, att: float):
    """Correct the ratio for a given attenuation on s21 input"""

    if att <= 0:
        return data
    else:
        # fron dB to float
        att = 10**(att/20) 

    ndata = []
    for i in range(len(data)):
        freq, re, im = data[i]
        orig = complex(re,im)
        # apply correction to complex, both real and imag
        corrected = orig * att
        ndata.append(Datapoint(freq, corrected.real, corrected.imag))

    return ndata
`

**Comment by satfan52** [comment]
Hello, I would like to be able to test a version of nanovna-saver with this "attenuationfunctionality" integrated"  (waiting for it to be merged if ever). Many thanks for sending the link to the test version so I can download it.

**Comment by zarath** [comment]
Implemented in v0.3.0

**Pull request closed without merging**
