### PR TITLE
Feature/delta marker

### PR DESCRIPTION
**Pull request by zarath**
Delta Marker can be enabled.
Normal markers are in scrollable area now.
Switched main layout from grid to box ...

### CODE REVIEW

**Comment by zarath** [comment]
> Looking good :)
Tried out, or just code review?

**Comment by RandMental** [comment]
Hi Holger

I noticed the auto formatting cuts off the 2nd column of the maker value and add a scroll bar.

 

When enabling the Delta marker, more of the 2nd column is visible, but not all.  (Second screen dump).

 

I am not sure how much formatting is available in python,  but I prefer the full maker info to be shown without a scroll bar at the bottom.   As indicated on the first screen dump, the column width can be decreased and the number of the decimal places possibly minimised to 3.   The NanoVna is not an accurate  measuring tool and having that number of decimal place is a waste of space.

 

No problem with Execution or crashes when build and run Win 10 64b

**Comment by Psynosaur** [comment]
on my 1440p monitor with a scale factor of 125%
image

I too see cut off

**Comment by zarath** [comment]
I have made the border between the marker and chart column movable. Better results?

**Comment by Psynosaur** [comment]
when adding markers the window resizes like this screen
image
when resizing the border it snaps back into place, also do notice the artificial border ( marked with red )  
image
Regards

**Comment by zarath** [comment]
Strange. That border should be movable ... on linux i get three dots between that marker scrollbar  and the charts

**Comment by RandMental** [comment]
Much better thanks

 

Another suggestion do we really need to Name the Serial port field?  The dropdown already indiacted Comx:

**Comment by RandMental** [comment]
Ignore previous comment – git got mixed up and it was from a 0.3.2 version

**Comment by RandMental** [comment]
This appears, but I cannot move the border with the mouse

**Comment by RandMental** [comment]
On a different Screen aspect ration I can close the marker Window, but cannot resize it wider to see all the values

**Comment by Psynosaur** [comment]
I'll have a peek and revert

**Pull request merged**
