### PR TITLE
Refactoring vswr analisis

### PR DESCRIPTION
**Pull request by gaionim**
Hi,
only a sample to lock or concordate modification.
With MagLoopAnalysis I want "follow" and zoom on minimum.
1) scan 3-30 MHz
2) find minimum
3) scan  center minimum + initial span 
4) find minimum , if no minimum increase span and goto 3
5) show data es Q
6) ajust loop capacitor
7) goto 3

I also want to create EndFedAnalisis to find N minimum and zoom on those minimum.
It will help if Chart can have its  data to show.
Sorry for my bad english, but with some ask I can explain better

### CODE REVIEW

**Comment by gaionim** [comment]
some data for testing
[sampleData.zip](https://github.com/mihtjel/nanovna-saver/files/3854071/sampleData.zip)

**Comment by mihtjel** [comment]
I'm definitely going to look at this more closely - but, time! :-/ Thanks for contributing, though!

**Comment by gaionim** [comment]
>  but, time! :-/ 
me too ;-)
See also https://github.com/gaionim/nanovna-saver/tree/follow
With analysis "run automatically" and "continuous sweep" it  change frequency, but often fail reading data. 
Out of index because 102 values :-(
If I run sweep manually seems to work.

**Comment by gaionim** [comment]
reopened https://github.com/NanoVNA-Saver/nanovna-saver/pull/213 against new code

**Pull request closed without merging**
