### PR TITLE
Add support for V2

### PR DESCRIPTION
**Pull request by nanovna**
This patch adds support for V2 (S-A-A-2) hardware.

I have only tested this on Linux (debian), consider testing more platforms and more V1 device/firmware variants to make sure it doesn't break anything before merging.

### CODE REVIEW

**Comment by mihtjel** [comment]
Hi,
thanks for these updates. Is there documentation for the protocol used with the "NanoVNA V2"? Is the hardware available yet "in the wild"?

**Comment by nanovna** [comment]
There is a preliminary user guide that has a description of the protocol:
[ug1101.pdf](https://github.com/mihtjel/nanovna-saver/files/4120622/ug1101.pdf)
See "Appendix II – USB data interface".

Some users have been sent sample/demo units.
If you would like a sample write to OwOwOwOwO123@outlook.com

Wide availability of the hardware will begin after Chinese New Year.

**Comment by goldstar611** [comment]
Hi @nanovna I have a PR open that may need adjusting if yours is merged first. Could I ask your help testing my PR with the v2 nanoVNA? It basically adds a "pause stimulus" serial command after scan/sweep. You should only need to add a `def pauseSweep` override in your class.

https://github.com/mihtjel/nanovna-saver/pull/173

Let me know if it works on the v2 nanoVNA, thanks!

**Comment by nanovna** [comment]
Hi, I'll be doing a rebase later after your patch is merged, and then I can fix any issues that come up.

**Comment by zarath** [comment]
I don't know when Rune gets time for working on NanoVNA-Saver again (and when he get's his V2).
In the mean time I've done some rebasing on nanavna's patch as well as Windows fixes on my fhttps://github.com/zarath/nanovna-saver/tree/feature/nanovna-v2 branch.

And as Rune noted somewhere, he isn't working on master branch, so he likes to get MRs to the Development branch.

Regards
  Holger

**Comment by zarath** [comment]
I have merged and adjusted the code for the current Development branch and made it available as master in my repository https://github.com/zarath/nanovna-saver.git

But not fixed that mentioned s21 issue

**Comment by zarath** [comment]
included in v0.3.0

**Pull request closed without merging**
