### PR TITLE
add macports installation instruction

### PR DESCRIPTION
**Pull request by ra1nb0w**

### CODE REVIEW

**Comment by ra1nb0w** [comment]
just a side note: the text font is not large enought on macOS and retina/4k displays. See the image. Changing to 10px is the temporary solution.

Screenshot 2020-04-06 at 11 11 30

**Comment by ra1nb0w** [comment]
ping

**Comment by zarath** [comment]
Pong...
Can you tell me from where the MacPorts are getting its NanoVNASaver versions?

**Comment by ra1nb0w** [comment]
the port can be see at https://ports.macports.org/port/NanoVNASaver/summary
I am using `https://github.com/mihtjel/nanovna-saver`; should I move to `https://github.com/NanoVNA-Saver/nanovna-saver`?

**Comment by zarath** [comment]
MacPorts distribution will be mentioned

**Pull request merged**
