### PR TITLE
NanoVNA-F and NanoVNA-F_V2

### PR DESCRIPTION
**Pull request by sysjoint-tek**
1. Modifications on nanovna-f:
Delete the code 41~64 lines of NanoVNA-F file (These codes will cause the screen to be divided into four pieces, and each piece will spread evenly to the full screen. After deleting these codes, the screenshot will be normal. I don’t know what these codes do?)

2. About the new NanoVNA-F_V2
Added recognition of NanoVNA-F_V2 models and screenshots

### CODE REVIEW

**Comment by zarath** [comment]
Thanks for your contribution. I'll think I'll find time to review it tomorrow evening... I hope I can convince some other OMs for testing -F Variants as I don't personally own one.
But otherwise your code looks good and will not break functionality on other targets.

**Comment by zarath** [comment]
Can I ask you to rebase your changes next time so that these deletion and recreation commits are not in the history?

I sometimes do the same mistake, but I hope I can keep the commit log cleaner in future.

**Comment by Kimalakia** [comment]
> Can I ask you to rebase your changes next time so that these deletion and recreation commits are not in the history?
> 
> I sometimes do the same mistake, but I hope I can keep the commit log cleaner in future.

Ok, I will, thanks for your suggestion.

**Comment by sysjoint-tek** [comment]
> Can I ask you to rebase your changes next time so that these deletion and recreation commits are not in the history?
> 
> I sometimes do the same mistake, but I hope I can keep the commit log cleaner in future.

Ok, I will, thanks for your suggestion!

**Pull request merged**
